"""
emit_tables.py — WS6: regenerate every data-driven manuscript .tex table from the
single source of truth (results_COSE/NUMBERS.json) into manuscript_COSE/tables/.

Generated tables (the manuscript \\input{}s these):
  * tab:certificate  certificate_coverage.tex   (REAL, CPU-reproducible)
  * tab:adaptive     adaptive.tex                (from adaptive 5-seed agg, if present)
  * tab:main         main_results.tex            (from in-domain 5-seed agg, if present)
  * tab:recovery     recovery.tex                (from recovery 5-seed agg, if present)

tab:positioning and tab:taxonomy stay MANUAL (they encode qualitative claims, not
measured numbers) and are not touched.

Honest-by-construction: a table whose data is still PENDING in NUMBERS.json
(the SOTA/CANOPI cells needing a GPU run) is NOT fabricated. emit_tables writes a
clearly-marked stub .tex for it and reports it as pending, so a \\input never
silently injects an invented number; the manuscript keeps its inline placeholder
until the GPU run populates NUMBERS.json.
"""
from __future__ import annotations

import json
import os
from typing import Optional

TABLES_DIR = "manuscript_COSE/tables"
_HEADER = "% AUTO-GENERATED by code/emit_tables.py from results_COSE/NUMBERS.json -- do not edit by hand.\n"


def _tex_escape(s: str) -> str:
    """Escape the LaTeX-special characters that appear in detector/family names."""
    return str(s).replace("\\", r"\textbackslash{}").replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


# Internal detector keys -> the display names the manuscript prose uses. Anything not
# listed falls back to a LaTeX-escaped version of the raw key.
_DISPLAY = {
    "regex": "Regex baseline",
    "tfidf_svm": r"B1 TF--IDF{+}LinearSVM",
    "protectai/deberta": "B2 DeBERTa-v3",
    "InjecGuard": "B3 InjecGuard",
    "CANOPI": "CANOPI (joint)",
    "B5_embedding": "B5 embedding",
    "B6_invariance": "B6 invariance-only",
    "B7_pauc": "B7 partial-AUC-only",
}


def _name(key: str) -> str:
    """Manuscript display name for a detector key, LaTeX-safe."""
    return _DISPLAY.get(key, _tex_escape(key))


def _stub(name: str, exp: str) -> str:
    return (_HEADER +
            f"% PENDING: experiment '{exp}' has no 5-seed data in NUMBERS.json yet.\n"
            f"% It requires the GPU SOTA/CANOPI run (transformers + sentence-transformers).\n"
            f"% The manuscript keeps its inline single-seed placeholder for {name} until then.\n")


def _fmt_ci(rec: dict, prec: int = 3) -> str:
    """Format a {mean,std,ci_lo,ci_hi} record as 'mean$\\pm$std' (CI in a footnote col
    elsewhere). Falls back to a bare value if no std."""
    m = float(rec["mean"])
    if rec.get("std") not in (None, "", "nan"):
        return f"{m:.{prec}f} $\\pm$ {float(rec['std']):.{prec}f}"
    return f"{m:.{prec}f}"


# --------------------------------------------------------------------------
# tab:certificate
# --------------------------------------------------------------------------
def emit_certificate(numbers: dict) -> Optional[str]:
    sec = numbers.get("certificate", {}).get("numbers_snapshot_certificate")
    if not sec:
        return None
    inv = sec["per_detector_invariance"]
    fams = sec["families"]
    order = ["confusable_known", "confusable_tr39", "smallcap_oom", "invisible_tag",
             "structural", "semantic"]
    L = [_HEADER.rstrip("\n"),
         r"\begin{table}[t]\centering",
         r"\caption{Certificate coverage by attack family. Coverage is the fraction of "
         r"obfuscated attacks inside the canonical closure $\mathcal{C}_D$, hence provably "
         r"defeated (0\% attack success against any detector, Theorem~\ref{thm:invariance}). "
         f"Idempotence $={sec['idempotence']:.2f}$; closure-soundness rises from "
         f"${sec['closure_soundness_base_map']:.3f}$ (40-entry base map) to "
         f"${sec['closure_soundness_full_table']:.4f}$ (full UTS\\#39 table); per-detector "
         r"decision invariance over the closure is " +
         ", ".join(f"{_tex_escape(k)}~${v:.2f}$" for k, v in inv.items()) +
         f"; the full-table fold flips ${sec.get('fpr_neutral_max_flip_rate', 0.0):.2f}$ benign "
         f"decisions on {sec.get('fpr_neutral_benign_n','')} prompts including non-Latin text.}}",
         r"\label{tab:certificate}", r"\small", r"\begin{tabular}{llcc}", r"\toprule",
         r"Attack family & Type & Coverage in $\mathcal{C}_D$ & Residual \\", r"\midrule"]
    for fam in order:
        if fam not in fams:
            continue
        r = fams[fam]
        typ = "semantic" if r.get("semantic") else "info-preserving"
        L.append(f"{fam.replace('_',' ')} & {typ} & {r['coverage']:.3f} & {r['residual']:.3f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------
# tab:adaptive  (from adaptive_v2_matrix_agg, 5-seed)
# --------------------------------------------------------------------------
# Family key -> the manuscript's display label and ordering for tab:adaptive.
_FAM_LABEL = [
    ("confusable_known", "confusable (in-table)"),
    ("confusable_tr39", "confusable (TR39)"),
    ("smallcap_oom", "small-capital"),
    ("invisible_tag", "invisible / Tag"),
    ("structural", "structural"),
    ("semantic", "semantic (no-op)"),
]


def _cell(r, key):
    """mean $\\pm$ std for an adaptive cell, formatted to 2 dp like the manuscript."""
    m = r.get(f"{key}_mean", "")
    s = r.get(f"{key}_std", "")
    if m in ("", None):
        return ""
    try:
        # show the +/- term only when it is non-negligible at the table's 2-dp precision
        if s not in ("", None, "nan") and round(float(s), 2) >= 0.01:
            return f"{float(m):.2f} $\\pm$ {float(s):.2f}"
        return f"{float(m):.2f}"
    except (TypeError, ValueError):
        return str(m)


def emit_adaptive(numbers: dict, detector: str = "InjecGuard") -> Optional[str]:
    sec = numbers.get("adaptive", {})
    agg = sec.get("adaptive_v2_matrix_agg")
    if not agg:
        return None
    # The manuscript's tab:adaptive is the held-out LOFO sweep on InjecGuard, the
    # detector most vulnerable to obfuscation (its caption, prose, and figure all say
    # so); the full multi-detector matrix lives in adaptive_v2_matrix_agg.csv.
    by_fam = {r["heldout_family"]: r for r in agg if r.get("detector") == detector}
    if not by_fam:
        return None
    L = [_HEADER.rstrip("\n"),
         r"\begin{table}[t]\centering",
         r"\caption{Defense-aware adaptive attacker, leave-one-family-out. Worst-case "
         r"$\mathrm{R@1\%FPR}$ found by an optimizer that perturbs then applies the known "
         r"defense, for the held-out family on InjecGuard (the detector most vulnerable to "
         r"obfuscation), as 5-seed mean $\pm$ s.d. Higher is better for the defense.}",
         r"\label{tab:adaptive}", r"\small", r"\begin{tabular}{lccc}", r"\toprule",
         r"Held-out family & No defense & $c$ (base) & $c^{+}$ (hardened) \\", r"\midrule"]
    for key, label in _FAM_LABEL:
        if key not in by_fam:
            continue
        r = by_fam[key]
        L.append(f"{label} & {_cell(r,'none')} & {_cell(r,'c')} & {_cell(r,'cplus')} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------
# tab:main  (in-domain, 5-seed)
# --------------------------------------------------------------------------
def emit_main(numbers: dict) -> Optional[str]:
    sec = numbers.get("in_domain", {})
    agg = sec.get("main_results_agg")
    if not agg:
        return None
    L = [_HEADER.rstrip("\n"),
         r"\begin{table}[t]\centering",
         r"\caption{In-domain detection on xTRam1, $\mathrm{R@1\%FPR}$ (5-seed mean $\pm$ "
         r"s.d.; external baselines are single-valued, so their s.d. is $0$). The benchmark "
         r"is in-domain-saturated; the joint objective gives no advantage over its ablations, "
         r"which is why our contribution is the certified primitive and its adaptive "
         r"evaluation, not an in-domain accuracy gain.}",
         r"\label{tab:main}", r"\small", r"\begin{tabular}{lc}", r"\toprule",
         r"Detector & $\mathrm{R@1\%FPR}$ \\", r"\midrule"]
    for r in agg:
        val = r.get("value") or (f"{float(r['mean']):.3f} $\\pm$ {float(r['std']):.3f}"
                                 if r.get("std") not in (None, "", "nan") else f"{float(r['mean']):.3f}")
        L.append(f"{_name(r.get('detector',''))} & {val} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------
# tab:recovery (5-seed)
# --------------------------------------------------------------------------
def emit_recovery(numbers: dict) -> Optional[str]:
    sec = numbers.get("recovery", {})
    agg = sec.get("recovery_matrix_agg")
    if not agg:
        return None
    L = [_HEADER.rstrip("\n"),
         r"\begin{table}[t]\centering",
         r"\caption{Detector-agnostic recovery, $\mathrm{R@1\%FPR}$ attacked vs. "
         r"+canonicalization (5-seed mean $\pm$ s.d.).}",
         r"\label{tab:recovery}", r"\small", r"\begin{tabular}{lll}", r"\toprule",
         r"Detector & Attack & Attacked $\to$ +canon \\", r"\midrule"]
    for r in agg:
        L.append(f"{_name(r.get('detector',''))} & {_tex_escape(r.get('attack',''))} & "
                 f"{r.get('recall_attacked_mean','')} $\\to$ {r.get('recall_recovered_mean','')} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


GENERATORS = {
    "certificate_coverage.tex": ("tab:certificate", "certificate", emit_certificate),
    "adaptive.tex":             ("tab:adaptive", "adaptive", emit_adaptive),
    "main_results.tex":         ("tab:main", "in_domain", emit_main),
    "recovery.tex":             ("tab:recovery", "recovery", emit_recovery),
}


def emit(numbers_path: str = "results_COSE/NUMBERS.json", tables_dir: str = TABLES_DIR) -> dict:
    numbers = json.load(open(numbers_path))
    os.makedirs(tables_dir, exist_ok=True)
    written, pending = [], []
    for fname, (label, exp, gen) in GENERATORS.items():
        content = gen(numbers)
        path = os.path.join(tables_dir, fname)
        if content is None:
            open(path, "w").write(_stub(label, exp))
            pending.append(label)
        else:
            open(path, "w").write(content)
            written.append(label)
    print(f"emit_tables -> {tables_dir}: written={written} pending(stub)={pending}")
    return {"written": written, "pending": pending}


if __name__ == "__main__":
    emit()
